### ISSUE TITLE
Apply API key security to REST API

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/indy-catalyst#284]
- [ ] Add a command line parameter to run with no API key
- [ ] Add another parameter to manually specify the API key (or environment variable?)
- [ ] Otherwise randomly generate an API key and print it to the console
- [ ] Add API key support to the swagger UI

**Comment by kdenhartog** [comment]
I've been looking into API security and I think we're going to need to require HTTPS for this work, rather than HTTP. Otherwise I believe that the API keys can be sniffed and stolen.

I've opened an Aries issues to discuss this in the broader community. https://github.com/hyperledger/aries-rfcs/issues/97
